file name

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,15 +1,26 @@
 #!/bin/bash
 
-echo "[Compiling...]"
-clang++-6.0 $1.cpp -std=c++2a -Wall -Wextra -pedantic
-
-if [ $? -eq 0 ]; then
-    echo "[Running...]"
-    ./a.out
-
-    echo "[Cleaning...]"
-    rm a.out
-else
-    :
+if [ -z "$COMPILER" ]; then
+    COMPILER="clang++-6.0"
+    OPTS="-std=c++2a"
 fi
+
+files=`find . -maxdepth 1 -name "$1*.cpp"`
+if [ -z "${files// }" ]; then
+    echo "[cannot find file starting with \"$1\"]"
+    exit 1
+fi
+
+echo "[Compiling with $COMPILER]"
+"$COMPILER" $files $OPTS -Wall -Wextra -pedantic
+
+if [ $? -ne 0 ]; then
+    exit 1
+fi
+
+echo "[Running...]"
+./a.out
+
+echo "[Cleaning...]"
+rm a.out
 
